name: Deploy para FTP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy FTP
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Deploy via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.6
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: ${{ secrets.FTP_DIR }}
          exclude: |
            **/.git*
            **/.git*/**
            .github/**
            scripts/**
            README.md
